### ISSUE TITLE
Run fails when result output is too large

### ISSUE THREAD

**Issue by chanks** [jeremyevans/minitest-parallel_fork#4] opened 2018-04-27 21:18 UTC
I've started trying to integrate this gem into a project, but I'm running into a problem - when the spec run is wrapping up, the child processes seem to hang at the writing of the marshalled data. After googling a bit I think I'm running into the issue in this SO answer: https://stackoverflow.com/a/14431021 - specifically, that there's a maximum amount of data that can be held in the pipe at once, and that the children are blocking until the parent empties the pipe, but the parent blocks until the children all exit, so the system deadlocks.

I'm not sure offhand of the best way to fix this, possibly the parent process should be iterating over the pipes, extracting/appending data as it becomes available, and then only unmarshalling it all as the children finish.

I don't know much about the IO interface, but if that seems reasonable I can try to put a pull request together next week.

Edit to add: I patched the gem so that the children would return `[0, 0, []]` instead of the actual results and the spec run was able to finish successfully (though with the wrong values, of course), is another reason why I think this is the issue. Also I'm running Linux Mint - it seems like pipe behavior is OS-dependent.

**Comment by jeremyevans** [comment] 2018-04-27 21:27
I've noticed this issue too, and your root cause analysis seems correct to me.  I've just been lazy and rerun the specs without parallel fork when I've hit this. :)  If you want to work on a fix for this, I would definitely appreciate it.  Otherwise, I may be able to work on a fix next week.

**Comment by chanks** [comment] 2018-04-27 22:10
Alright, cool. My next open-source day at work is on Friday, I can try to get to it then.

**Comment by ksol** [comment] 2018-05-02 15:39
👍 I noticed the same issue this afternoon, which (for me) manifests when there is a good number of failures/errors, so that would corroborate the pipe size hypothesis (I probably won't have the time to try and find a fix before a little while though)

**Closed** 2018-05-07 23:52 UTC
